[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 15

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 16

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20



[[footer]]
  name = "Impressum"
  pageRef = "impressum"

[[footer]]
  name = "Privacy"
  pageRef = "privacy"


